### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by theiskaa** [theiskaa/field_suggestion#36]
### Subtasks of general improvements:

---

- [ ] 1. Improve documentation design, add better text field examples.

---

- [ ] 2. Improve doc/code comments to make codes more understandable for other developers

---

- [ ] 2. Redesign/Improve logo

---
